appcontact/urls.py
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('appcontact.views',
    url(r'^$','index',name='index'),
    url(r'^contacto$','contact_form',name='contact_form'),
    url(r'^inicio$','inicio',name='inicio'),
    url(r'^logout$','logoff',name='logoff'),
    url(r'^mycontacts','mycontacts',name='mycontacts'),
    url(r'^detailcontact/(?P<idc>\d+)/$','detailcontact',name='detailcontact'),
    url(r'^edtcontact/(?P<idc>\d+)/$','edtcontact',name='edtcontact'),
    url(r'^delcontact/(?P<idc>\d+)/$','delcontact',name='delcontact'),
    url(r'^resultados$','resultados',name='resultados'),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += patterns('appcontact.restviews',
    url(r'^login$','login',name='login'),
    url(r'^addcontact$','addcontact',name='addcontact'),
    url(r'^addphoto$','addphoto',name='addphoto'),
    url(r'^delphoto/(?P<idu>\d+)/$','delphoto',name='delphoto'),
    url(r'^location$','restlocation',name='restlocation'),
    url(r'^addtag/$','addtag',name='addtag'),
    url(r'^colonia$','colonia',name='colonia'),
    url(r'^addnote$','addnote',name='addnote'),

    
)

appentity/urls.py
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('appentity.views',
    url(r'^entity','entity',name='entity'),
    url(r'^myentities','myentities',name='myentities'),
    url(r'^entity','entity',name='entity'),
    url(r'^detailentity/(?P<ide>\d+)/$','detailentity',name='detailentity'),
    url(r'^editentity/(?P<ide>\d+)/$','editentity',name='editentity'),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += patterns('appentity.restviews',
    url(r'^addphotoentity$','addphoto',name='addphoto'),
    url(r'^edelphoto/(?P<idu>\d+)/$','delphoto',name='delphoto'),
    url(r'^addentity','addentity',name='addentity'),
 )

contactmanager/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    (r'^', include('appcontact.urls')),
    (r'^', include('appentity.urls')),

)

appcontact/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import simplejson


class ContactFiles(models.Model):
    type_file = models.CharField(max_length=200,blank=True)
    contact_file = models.FileField(upload_to='ContactFiles')
    '''
        status params 
         case 0 incomplete
         case 1 Complete
         case 2 Deleted
    '''
class Contact(models.Model):
    usercreator = models.ForeignKey(User)
    userrelated = models.IntegerField(null=True,blank=True)
    namec = models.CharField(max_length=200,blank=True,null=True)
    lastname = models.CharField(max_length=200,blank=True,null=True)
    chargec = models.CharField(max_length=100,blank=True,null=True)
    phones = models.TextField(blank=True,null=True)
    urls = models.TextField(blank=True,null=True)
    date_create = models.DateTimeField(default=datetime.now)
    photoc = models.IntegerField(blank=True,null=True)
    status = models.CharField(max_length=2,default=1)
    extrac = models.TextField(blank=True,null=True)
    tags = models.TextField(blank=True,null=True) 
    address = models.CharField(max_length=200)
    cp = models.CharField(max_length=10)
    colonia = models.CharField(max_length=200)
    delomun = models.CharField(max_length=200)
    estado = models.CharField(max_length=200)
    lon = models.FloatField(default=0)
    lat = models.FloatField(default=0)


    def photoimg(self):
        photoim = ContactFiles.objects.get(pk=self.photoc)
        return photoim

    def phone_list(self):
        listing = simplejson.loads(self.phones)
        return listing

    def socialinfo(self):
        listando = [x.social_accounts for x in self.contactsocialinfo_set.all()]
        return simplejson.loads(listando[0])

    def urls_list(self):
        if self.urls:
            listado = simplejson.loads(self.urls)
        else:
            listado = None
        return listado

    def tages(self):
        if self.tags:
            tags = simplejson.loads(self.tags)
            listing = tags
        else:
            listing = None
        return listing

class ContactSocialInfo(models.Model):
    Contact_id = models.ForeignKey(Contact)
    social_accounts = models.TextField()
    

class EmailList(models.Model):
    contacto = models.ForeignKey(Contact)
    email = models.EmailField()
    typeofemail = models.CharField(max_length=10,blank=True)


class Tag(models.Model):
    tagname = models.CharField(max_length=200,null=True,default='Untitle')
    def __unicode__(self):
        return '%s' %(self.tagname[0].upper())
    
class Sepomex(models.Model):
    codigo_postal = models.CharField(max_length=5)
    asentamiento = models.CharField(max_length=250)
    tipo_asentamiento = models.CharField(max_length=100)
    municipio = models.CharField(max_length=250)
    estado = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=250)
    descripcion_codigo_postal = models.CharField(max_length=5)
    clave_estado = models.CharField(max_length=2)
    clave_oficina = models.CharField(max_length=5)
    clave_tipo_asentamiento = models.CharField(max_length=5)
    clave_municipio = models.CharField(max_length=3)
    clave_asentamiento = models.CharField(max_length=2)
    zona = models.CharField(max_length=40)
    clave_ciudad = models.CharField(max_length=2)

class Note(models.Model):
    class Meta:
        ordering = ['date_create']
    text = models.TextField(default='untitle')
    sender = models.ForeignKey(User)
    receptor = models.ForeignKey(Contact)
    date_create = models.DateField(auto_now_add=True,default=datetime.now)

appcontact/views.py
# -*- encoding: utf-8 -*-
from django.http import HttpResponse
from django.template.context import RequestContext
from django.shortcuts import get_object_or_404, render_to_response
from contactmanager.forms import *
from appcontact.models import * 
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import redirect
from django.contrib.auth import logout
import string as STrg
from django.db.models import Q


# ********************************** DRY METHODS    ******************************************************


def abc_tag_list():
    ''' 
        This method need a Tag django-model
    '''
    a = {x:[] for x in STrg.ascii_uppercase}
    T = Tag.objects.all()
    for x in T:
        a['%s'%(x)].append({'tag':'%s'%(x.tagname)})
    return a

# VIEWS TO "THE SISTEMA" ----------------------------------------------------------


def index(request):
    context = RequestContext(request)
    user = request.user
    if user.is_active:
        return redirect('/inicio')
    return render_to_response("login.html",{},context)


@login_required(login_url="/")
def inicio(request):
    context = RequestContext(request)
    try: 
        myme = Contact.objects.get(userrelated=request.user.pk)
    except:
        myme = request.user
    return render_to_response("inicio.html",{'myme':myme},context)

@login_required(login_url='/')
def contact_form(request):
    context = RequestContext(request)
    forms_list = [{'fieldname':'phone','label':'Teléfono','plhdr':'(xx-xxxxxxx)'},
                  {'fieldname':'email','label':'Email','plhdr':'email@domine.something'},
                  {'fieldname':'url','label':'Sitio Web','plhdr':'http://www.domine'}
    ]
    if request.GET:
    #SE TRATA DE UNA EDICION DE DATOS
        contact = Contact.objects.get(pk=request.GET['idc'])
    else:
        contact = None

    try: 
        myme = Contact.objects.get(userrelated=request.user.pk)
    except:
        myme = request.user


    states=Sepomex.objects.distinct('estado').values('estado','clave_estado')

    return render_to_response('forms/contact_form.html',
                              {'lista':forms_list,
                              'contact':contact,
                              'myme':myme,
                              'states':states},
                              context)

@login_required(login_url='/')
def edtcontact(request,idc=None):
    context = RequestContext(request)
    forms_list = [{'fieldname':'phone','label':'Teléfono','plhdr':'(xx-xxxxxxx)'},
                  {'fieldname':'email','label':'Email','plhdr':'email@domine.something'},
                  {'fieldname':'url','label':'Sitio Web','plhdr':'http://www.domine'}
    ]
    try: 
        myme = Contact.objects.get(userrelated=request.user.pk)
    except:
        myme = request.user
   #SE TRATA DE UNA EDICION DE DATOS
    contact = Contact.objects.get(pk=idc)
    states=Sepomex.objects.distinct('estado').values('estado','clave_estado')
    return render_to_response('forms/edt_contact.html',{'lista':forms_list,'contact':contact,
                              'myme':myme,'states':states},context)

@login_required(login_url='/')
def delcontact(request,idc=None):
    context = RequestContext(request)
    contact = Contact.objects.get(pk=idc)
    contact.status=0
    contact.save()
    return redirect('/mycontacts')
    return render_to_response('forms/edt_contact.html',{'lista':forms_list,'contact':contact,'myme':myme},context)




@login_required(login_url='/')
def mycontacts(request):
    context = RequestContext(request)
    contacts = Contact.objects.filter(~Q(status=0)).order_by('-date_create')
    try: 
        myme = Contact.objects.get(userrelated=request.user.pk)
    except:
        myme = request.user
    abc = abc_tag_list()
    return render_to_response('mycontacts.html',{'contacts':contacts,'abc':abc,'myme':myme},context)


# DATAIL CONTACT*******************************************************************************************


@login_required(login_url='/')
def detailcontact(request,idc=None):
    context = RequestContext(request)
    
    try:
        c = Contact.objects.get(usercreator=request.user,pk=idc)
    except:
        c = None

    try: 
        myme = Contact.objects.get(userrelated=request.user.pk)
    except:
        myme = request.user

    return render_to_response('detailcontact.html',{'c':c,'myme':myme},context)

# SEARCH RESULTS *********************************************************************************************
def resultados(request):
    context = RequestContext(request)
    wordss = request.POST.get('words',None)
    kwargs = {'status':1}
    ekwargs = {} #{'status':1}
    args = Q()
    eargs = Q()
    namec = request.POST.get('namec',None)
    

    estado = request.POST.get('estado',None)
    tag = request.POST.get('tag',None)
    if namec:
        kwargs['namec']='%s'%(namec)
    if tag:
        kwargs['tags__icontains']="%s"%(tag)
    formdata = request.POST.copy()
    
    states = Sepomex.objects.all().distinct('estado')
    if estado:
        city = Sepomex.objects.filter(estado=estado).distinct('municipio')
        kwargs['estado']=estado
    else:
        city = None
    
    locations = [states,city]    
    
    if wordss:
        args = Q(namec__icontains=wordss)
        eargs = Q(nameac__icontains=wordss)
    
    response = []
    
    c = Contact.objects.filter(*[args],**kwargs)
    o = Entity.objects.filter(*[eargs],**ekwargs)
    
    for item in c:
        response.append({'name':item.namec,'type':'Contacto','photoimg':item.photoimg,'link':'/detailcontact/'+str(item.pk)+'/',
                         'state':item.estado,'address':item.address,'phones':item.phone_list
                        })
    for item in o:
        response.append({'name':item.nameac,'type':'Organización','photoimg':item.photoimg,'link':'/detailentity/'+str(item.pk)+'/',
                          'address':item.addressac,'phones':item.phones_list
                        })
    abc=abc_tag_list()
    try: 
        myme=Contact.objects.get(userrelated=request.user.pk)
    except:
        myme=request.user

    del formdata['csrfmiddlewaretoken']
    print kwargs
    return render_to_response('myresults.html',
                             {'response':response,
                              'abc':abc,'myme':myme,
                              'formdata':formdata,
                              'location':locations},
                              context)

def logoff(request):
    logout(request)
    return redirect('/')

appcontact/templates/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/chumbuket.css" %}" />
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/sitio.css" %}" />
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
       <script type="text/javascript" src="{% static "js/jquery-1.11.1.min.js"%}"></script>
        <script type="text/javascript" src=""></script>
        {% block kuppe %}{% endblock %}
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

appcontact/templates/base2.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "bootstrap/css/bootstrap.css" %}" />
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/chumbuket.css" %}" />
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
        
        
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "ui/jquery-ui.css" %}" />
        <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/sitio.css" %}" />
        <script type="text/javascript" src="{% static "js/jquery-1.11.1.min.js"%}"></script>
        <script type="text/javascript" src="{% static "ui/jquery-ui.js"%}"></script>
        {% block kuppe %}{% endblock %}
    </head>
    <body>
        <div class="table_n">
            <div class="table_r">
                <div class="table_c lefty">{% include "menu_left.html" %}</div>
                <div class="table_c">
                    <div id="top_right">
                        {% include "top_right.html"%}
                    </div>
                    <div>
                        <div id="inicio_box">
                            {% block content %}{% endblock %} 
                        </div>           
                    </div>
                </div>
            </div>
        </div>
                       
       
        
        </div>   
    </body>
</html>

appcontact/templates/detailcontact.html
{% extends 'base2.html'%}

{% block kuppe %}
<script type="text/javascript" src= "/static/js/chumbukcet.js"></script>
{% endblock %}

{% block content %}

<div  class="blind phateris" id="tagerbox">
    <form  method="post" class="tagger">
        {%csrf_token%}
        <input type="text" name="tag" />
        <input type="hidden" name="contactpk" value="{{c.pk}}" />
        <a href="#" class="link_green btn_add_tag">Agregar</a>
        <a href="#tagerbox" class="edipokill glyphicon glyphicon-remove-sign">&nbsp;</a>
    </form>
</div>


<div class="table_n">
    <div class="table_r white_box">
        <div style="width:70%;"  class="table_c detailleft">
            <div class="layout_box">
                <div class="inline_blocke">
                    {% if c.photoimg.contact_file.url %}
                        <img src="/static/{{c.photoimg.contact_file.url}}" height="41px" />
                    {% else %}
                        <img src="/static/images/nophoto.jpg" />
                    {% endif %}
                </div>
                <div class="inline_blocke info_list_contact">
                    <h2>{{c.namec}} {{c.lastname}}</h2>

                    <p class="t5 underline">{{c.chargec}}</p>
                    <p class="t5 underline"><a href="#" class="addtag">Agregar Etiqueta</a></p>
                    <p>Tags:</p>
                    <div id="tage_boxe">
                        {% for t in c.tages %}
                        <p class="inline_blocke t7">{{t}}</p>
                        {% endfor %}
                    </div>

                </div>
                </div>
                <br/>
                <div id="tabs">
                    <ul class="menu_notas">
                        <li class="inline_blocke checked"><a href="#tabs_1">Notas</a></li>
                        <li class="inline_blocke uncheked"><a href="#tabs_2">Email</a></li>
                    </ul>
                </div>
                <div class="layout_box">
                    <div>
                        <form action="/addnote" method="post" id="addnotes">
                        <div class="t5">Agregar una nota acerca de {{c.namec}}</div>
                        <textarea name="text" class="borderme"> </textarea>
                        {%csrf_token%}
                        <input type="hidden" name="sender" value="{{myme.userrelated}}" />
                        <input type="hidden" name="receptor" value="{{c.pk}}" />
                         <div class="alineador">
                         <input type="submit" value="Agregar nota" class="btn_green" />
                        </div>
                        </form>
                    </div>
                    <div class="notes_box">
                        {%for note in c.note_set.all|dictsort:"date_create" reversed %}
                        <div class="notes_list"> 
                            <div class="inline_blocke table_c" style="padding:1px 6px;"><img src="/static/images/sobre.gif" /></div>
                            <div class="inline_blocke table_c">
                                <div class="t6 fecha_s">{{note.date_create}}</div>
                                <div class="t7">Nota de <span class="sender">{{note.sender.contact_set.all.0.namec}}
                                    {{note.sender.contact_set.all.0.lastname}}</span>
                                </div>
                                <p class="t6 text">{{note.text}}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
        </div>
       <div id="" class="table_c graybox">
            <div class="table_n" style="height:40px;width:98%;margin.auto;">
                <div class="table_r">
                    <div class="table_c" style="text-align:left;">
                        <p class="contact_editor_lnk"><a href="/edtcontact/{{c.pk}}/" class="linker">Editar Persona</a></p>  
                    </div>
                    <div class="table_c" style="text-align:right;">
                        <a href="/delcontact/{{c.pk}}/" class="linker deleteperson">Eliminar Persona</a>
                    </div>
                </div>
            </div>
            
            <div class="table_n greenbox">
                <div class="table_r">
                    <p class="table_c" style="text-align:left;padding-left:18px;">Tareas</p>
                    <p class="table_c" style="text-align:right;padding-right:18px;">Agregar Tarea</p>
        
                </div> 
        </div>
            
                    {% include "tareas.html" %}
           <br/>
           <div class="greenbox"></div>
           <ul class="contact_info_box">
                <li><p class="t5">Email:</p></li>
                {% for m in c.emaillist_set.all %}
                <li><a href="mailto:{{m.email}}" class="linker_blue">{{m.email}}</a></li>
                {% endfor %}
                <li class="t5">Teléfono(s):</li>
                {% for tel  in c.phone_list %}
                <li><span class="t4 right_contact">{{tel.phones}}</span><span class="t5 right_contact"> {{tel.typephones}}</span></li>
                {% endfor %} 
            <li>
                <br/>
                <div>
                    <div class="t5">Localización:</div>
                    <div>
                        <br/>
                        <img src="/static/images/mapa.gif" />
                    </div>
                    <div class="t4 right_contact"><span class="t5">Calle:</span> {{c.address}}</div>
                    <div class="t4 right_contact"><span class="t5">Colonia:</span> {{c.colonia}}</div>
                    <div class="t4 right_contact"><span class="t5">Delegación oMunicipio:</span> {{c.delomun}}</div>
                    <div class="t4 right_contact"><span class="t5">Estado:</span> {{c.estado}}</div>
                    <div class="t4 right_contact"><span class="t5">C.P.:</span>{{c.cp}}</div>
                </div>
            </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

appcontact/templates/form.html
<style>
.inline_blocke{
    display:inline-block;display: -moz-inline-stack;display: inline-block;vertical-align: top;
    zoom: 1;*display: inline;text-align:justify;
}

.table{
        display:table;
        width:60%;
        min-width:300px;
        border:1px solid black;
    }

.tabler{
        display:table-row;
        vertical-align:bottom;
        text-align:center;
    }

.tablec{
    min-width:300px;
    margin:3px auto;
    border:1px solid gray;
    height:40px;
    vertical-align:middle;
    display:table-cell;
}

</style>


<div class="table">

    <div class="tabler">
    
        <div class="tablec inline_blocke">asdasdasd</div>
        <div class="tablec inline_blocke">asdaaaaaaaaaaaaaaaaaa</div>


    </div>

</div>

appcontact/templates/header.html
<div id="header_box">
    <div id="logo" class="inline_blocke"><a href="/" class="inline_blocke">D4</a></div>
    <ul id="menu_list" class="inline_blocke">
        <li class="inline_blocke"><a href="/contacto">Nuevo contacto</a></li>
        <li class="inline_blocke"><a href="/entity">Nueva Organización</a></li>
        <li class="inline_blocke"><a href="/logout">Salir</a></li>
        <li class="inline_blocke"></li>
     </ul>
</div>

appcontact/templates/login.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block kuppe %}
    <script src="{% static "js/auth.js" %}"></script>
{% endblock %}

{% block content %}

    <div id="boxlogin">
        <div id="head_login">login</div>
        <form name="login" id="login"  method="post" action="auth">
            {% csrf_token %}
            <div>
                <label to="usr">Nombre de usuario</label>
                <input class="" type="text" name="usr" id="usr" tabindex="1" />
            </div>
            <div>
                <label to="pwd">Contraseña</label>
                <input type="password" name="pwd" id="pwd" tabindex="2" />
            </div>
            <div id="box_to_save">
                <span class="inline_blocke" id="recordar_box"><input type="checkbox" name="recordar" />&nbsp;&nbsp;&nbsp;recordar</span>
                <span class="inline_blocke" id ="saver_box"><input type="submit" class="btn_green" value="LOGIN" /></span>
            </div>
        </form>
    </div>
    

{% endblock %}

appcontact/templates/mycontacts.html
{% extends 'base2.html'%}
{% load tager %}

{% block content %}
<div class="table_n">
    <div class="table_r white_box">
            <div id="layout_box" class="table_c">
                <div id="headbar">Mis Contactos.</div>
                <div class="t6" style="text-align:left;padding:2px 14px;">
                    {% include 'forms/search_form.html' %}
                </div>
                <ul id="list_results">
                    {% for c in contacts %}
                    <li>
                        <div class="inline_blocke boxy">&nbsp;</div>
                        {% if c.photoimg.contact_file.url %}
                        <div class="inline_blocke myminiphoto" style="background-image:url(/static/{{c.photoimg.contact_file.url}});">
                            <a href="/detailcontact/{{c.pk}}/" class="inline_blocke" style="width:100%;height:100%;">&nbsp;</a>
                        </div>
                        {% else %}
                        <div class="inline_blocke"><img src="/static/images/nophoto.jpg" /></div>
                        {% endif %}
                        <div class="inline_blocke">
                            <a href="/detailcontact/{{c.pk}}/" class="t4">
                            <p>{{c.namec}}</p>
                            <p>
                            {% for geoinfo in c.contactgeoinfo_set.all%}
                            <div class="t5">{{geoinfo.address}} , {{geoinfo.cp}}</div>
                            {% endfor %}
                            </p>
                            {% for f in c.phone_list %}
                            <p class="inline_blocke t5">{{f.phones}}</p>
                            {% endfor %}
                            <br/>
                            {% for m in c.emaillist_set.all %}
                            <p class="inline_blocke t5">{{m.email}}</p>
                            {% endfor %}
                            </a>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        <div id="tagbox" class="table_c">
            <div class="t4">Buscar por etiquetas</div>
            <br/>
            <ul id="taglist">
                {% for x,y in abc.items %}
                    {% if y %}
                    <li>
                        <span class="table_c">{{x}}</span>
                        <span class="table_C">
                        {% for v in y %}
                            <div class="inline_blocke"><a href="#{{v.tag}}">{{v.tag}}</a></div>
                        {% endfor %}
                        </span>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

appcontact/templates/myresults.html
{% extends 'base2.html'%}

{% load staticfiles %}


{% block kuppe %}
     <script type="text/javascript" src="{% static "js/validations.js" %}"></script>
     <script type="text/javascript" src="{% static "js/forms.js" %}"></script>
{% endblock %}



{% block content %}
   
<div class="table_n">
    <div class="table_r white_box">
            <div id="layout_box" class="table_c">
                <div id="headbar">Resultados de Búsqueda:</div>
                <div class="t6" style="text-align:left;padding:2px 14px;">
                    {% include "forms/search_form.html"%}
                </div>
                <ul id="list_results">
                    {% for c in response  %}
                    <li>
                        <a href="{{c.link}}" class="t4">
                        <div class="inline_blocke boxy">&nbsp;</div>
                        {% if c.photoimg.entity_file.url %}
                        <div class="inline_blocke myminiphoto" style="background-image:url(/static/{{c.photoimg.entity_file.url}});">&nbsp;</div>
                         {% elif c.photoimg.contact_file.url %}
                        <div class="inline_blocke myminiphoto" style="background-image:url(/static/{{c.photoimg.contact_file.url}});">&nbsp;</div>
                        {% else %}
                        <div class="inline_blocke myminiphoto" style="background-image:url(/static/images/nophoto.jpg);"/></div>
                        {% endif %}
                        <div class="inline_blocke">
                            <p class="t5">{{c.type}}</p>
                            <p>{{c.name}}</p>
                            <p class="t5">{{c.address}}</p>
                            {% for p in c.phones %}
                                {% if p.phones %}
                                    <p class="t5">{{p.phones}}</p>
                                {% else %}
                                    <p class="t5">{{p.phone}}</p>
                                {% endif %}
                            {% endfor %}
                            {% for m in c.emaillist_set.all %}
                            <p class="inline_blocke t5">{{m.email}}</p>
                            {% endfor %}
                        </div>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        <div id="tagbox" class="table_c">
            <div class="t4">Buscar por etiquetas</div>
            <br/>
            <ul id="taglist">
                 {% for x,y in abc.items %}
                    {% if y %}
                    <li>
                        <span class="table_c">{{x}}</span>
                        <span class="table_C">
                        {% for v in y %}
                            <div class="inline_blocke"><a href="#{{v.tag}}" class="tagger">{{v.tag}}</a></div>
                        {% endfor %}
                        </span>
                    </li>
                    {% endif %}
                {% endfor %}
              </ul>
        </div>
    </div>
</div>
{% endblock %}

appcontact/templates/top_right.html
<ul>
    <li class="inline_blocke">
        <div class="btn_green inline_blocke">+<a href="/contacto">Contacto</a></div>
        <div class="btn_green inline_blocke">+<a href="/entity">Organización</a></div>
    </li>
    <li class="inline_blocke form_search">
        <form name="srch" id="srch" method="post" action="/resultados">
            {%csrf_token%}
            <input type="text" name="words" maxlength="100" class="inline_blocke" style="margin-top:4px;margin-left:12px;width:90%;"/>
            <input type="submit" id="buscadore" value="&nbsp;" style="background:url(/static/images/buscar.jpg);width:30px;" />
        </form>
    </li>
   <!--  <li class="inline_blocke"><div class="inline_blocke" id="msgr"><a href="#msgr">0</a></div></li> -->
    <li class="inline_blocke">
        <div class="inline_blocke" id="nameplace">
            <span class="name_c">{{myme.namec}}</span>
            <span class="last_name_c">{{myme.lastname}}</span>
        </div>
    </li>
    <li class="inline_blocke">
        <div style="background-image:url(/static/{{myme.photoimg.contact_file.url}});" class="myminiphoto inline_blocke"/>
    </li>
    <li class="inline_blocke">
        <a href="/logout" class="linker">Logout</a>
    </li>
</ul>